# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Second language.
# NOTE: Navigation menus are defined ONLY in menus.yaml / menus.zh.yaml.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 传鹏的实验室
  description: 传鹏的实验室
